import {
  applyDateDefault,
  applyDateTimeDefault,
  applyNumberDefault,
  applyNumberOrStringifyDefault,
} from "@/helper/vifHelper";
import type { VIFDescriptor } from "@/types";
import { decadeRange } from "@/vif/vifRange";

// The unit and the scaling exponent of every entry which is a scaled number
// were cross checked against libmbus (mbus-protocol.c) and FHEM (WMBus.pm) on
// 2026-09-05: all 100 respectively 121 comparable entries matched. Entries
// which are not a scaled number - dates, time points and special functions -
// are not covered by that check.
export const defaultVIFs: VIFDescriptor[] = [
  ...decadeRange(0x00, 8, -3, "VIF_ENERGY_WATT", "Wh", "Energy"),
  ...decadeRange(0x08, 8, 0, "VIF_ENERGY_JOULE", "J", "Energy"),
  ...decadeRange(0x10, 8, -6, "VIF_VOLUME", "m³", "Volume"),
  ...decadeRange(0x18, 8, -3, "VIF_MASS", "kg", "Mass"),
  {
    vif: 0x20,
    legacyName: "VIF_ON_TIME",
    unit: "s",
    description: "On Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x21,
    legacyName: "VIF_ON_TIME",
    unit: "min",
    description: "On Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x22,
    legacyName: "VIF_ON_TIME",
    unit: "h",
    description: "On Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x23,
    legacyName: "VIF_ON_TIME",
    unit: "d",
    description: "On Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x24,
    legacyName: "VIF_OP_TIME",
    unit: "s",
    description: "Operating Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x25,
    legacyName: "VIF_OP_TIME",
    unit: "min",
    description: "Operating Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x26,
    legacyName: "VIF_OP_TIME",
    unit: "h",
    description: "Operating Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x27,
    legacyName: "VIF_OP_TIME",
    unit: "d",
    description: "Operating Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  ...decadeRange(0x28, 8, -3, "VIF_ELECTRIC_POWER", "W", "Power"),
  ...decadeRange(0x30, 8, 0, "VIF_THERMAL_POWER", "J/h", "Power"),
  ...decadeRange(0x38, 8, -6, "VIF_VOLUME_FLOW", "m³/h", "Volume Flow"),
  ...decadeRange(
    0x40,
    8,
    -7,
    "VIF_VOLUME_FLOW_EXT1",
    "m³/min",
    "Volume Flow ext."
  ),
  ...decadeRange(
    0x48,
    8,
    -9,
    "VIF_VOLUME_FLOW_EXT2",
    "m³/s",
    "Volume Flow ext."
  ),
  ...decadeRange(0x50, 8, -3, "VIF_MASS_FLOW", "kg/h", "Mass Flow"),
  ...decadeRange(0x58, 4, -3, "VIF_FLOW_TEMP", "°C", "Flow Temperature"),
  ...decadeRange(0x5c, 4, -3, "VIF_RETURN_TEMP", "°C", "Return Temperature"),
  ...decadeRange(0x60, 4, -3, "VIF_TEMP_DIFF", "K", "Temperature Difference"),
  ...decadeRange(
    0x64,
    4,
    -3,
    "VIF_EXTERNAL_TEMP",
    "°C",
    "External Temperature"
  ),
  ...decadeRange(0x68, 4, -3, "VIF_PRESSURE", "bar", "Pressure"),
  {
    vif: 0x6c,
    legacyName: "VIF_TIME_POINT_DATE",
    unit: "",
    description: "Time point",
    calc: (val) => val,
    apply: applyDateDefault,
  },
  {
    vif: 0x6d,
    legacyName: "VIF_TIME_POINT_DATE_TIME",
    unit: "",
    description: "Time point",
    calc: (val) => val,
    apply: applyDateTimeDefault,
  },
  {
    vif: 0x6e,
    legacyName: "VIF_HCA",
    unit: "",
    description: "Units for H.C.A.",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x70,
    legacyName: "VIF_AVERAGING_DURATION",
    unit: "s",
    description: "Averaging Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x71,
    legacyName: "VIF_AVERAGING_DURATION",
    unit: "min",
    description: "Averaging Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x72,
    legacyName: "VIF_AVERAGING_DURATION",
    unit: "h",
    description: "Averaging Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x73,
    legacyName: "VIF_AVERAGING_DURATION",
    unit: "d",
    description: "Averaging Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x74,
    legacyName: "VIF_ACTUALITY_DURATION",
    unit: "s",
    description: "Actuality Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x75,
    legacyName: "VIF_ACTUALITY_DURATION",
    unit: "min",
    description: "Actuality Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x76,
    legacyName: "VIF_ACTUALITY_DURATION",
    unit: "h",
    description: "Actuality Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x77,
    legacyName: "VIF_ACTUALITY_DURATION",
    unit: "d",
    description: "Actuality Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x78,
    legacyName: "VIF_FABRICATION_NO",
    unit: "",
    description: "Fabrication No",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x79,
    legacyName: "VIF_OWNER_NO",
    unit: "",
    description: "Owner No",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x7a,
    legacyName: "VIF_BUS_ADDRESS",
    unit: "",
    description: "Bus Address",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
];
