import {
  applyDateDefault,
  applyDateTimeDefault,
  applyNumberDefault,
  applyNumberOrStringifyDefault,
  divide,
  multiply,
} from "@/helper/vifHelper";
import type { VIFDescriptor } from "@/types";

export const defaultVIFs: VIFDescriptor[] = [
  {
    vif: 0x00,
    legacyName: "VIF_ENERGY_WATT",
    unit: "Wh",
    description: "Energy",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x01,
    legacyName: "VIF_ENERGY_WATT",
    unit: "Wh",
    description: "Energy",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x02,
    legacyName: "VIF_ENERGY_WATT",
    unit: "Wh",
    description: "Energy",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x03,
    legacyName: "VIF_ENERGY_WATT",
    unit: "Wh",
    description: "Energy",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x04,
    legacyName: "VIF_ENERGY_WATT",
    unit: "Wh",
    description: "Energy",
    calc: (val) => multiply(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x05,
    legacyName: "VIF_ENERGY_WATT",
    unit: "Wh",
    description: "Energy",
    calc: (val) => multiply(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x06,
    legacyName: "VIF_ENERGY_WATT",
    unit: "Wh",
    description: "Energy",
    calc: (val) => multiply(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x07,
    legacyName: "VIF_ENERGY_WATT",
    unit: "Wh",
    description: "Energy",
    calc: (val) => multiply(val, 10000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x08,
    legacyName: "VIF_ENERGY_JOULE",
    unit: "J",
    description: "Energy",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x09,
    legacyName: "VIF_ENERGY_JOULE",
    unit: "J",
    description: "Energy",
    calc: (val) => multiply(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x0a,
    legacyName: "VIF_ENERGY_JOULE",
    unit: "J",
    description: "Energy",
    calc: (val) => multiply(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x0b,
    legacyName: "VIF_ENERGY_JOULE",
    unit: "J",
    description: "Energy",
    calc: (val) => multiply(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x0c,
    legacyName: "VIF_ENERGY_JOULE",
    unit: "J",
    description: "Energy",
    calc: (val) => multiply(val, 10000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x0d,
    legacyName: "VIF_ENERGY_JOULE",
    unit: "J",
    description: "Energy",
    calc: (val) => multiply(val, 100000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x0e,
    legacyName: "VIF_ENERGY_JOULE",
    unit: "J",
    description: "Energy",
    calc: (val) => multiply(val, 1000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x0f,
    legacyName: "VIF_ENERGY_JOULE",
    unit: "J",
    description: "Energy",
    calc: (val) => multiply(val, 10000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x10,
    legacyName: "VIF_VOLUME",
    unit: "m³",
    description: "Volume",
    calc: (val) => divide(val, 1000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x11,
    legacyName: "VIF_VOLUME",
    unit: "m³",
    description: "Volume",
    calc: (val) => divide(val, 100000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x12,
    legacyName: "VIF_VOLUME",
    unit: "m³",
    description: "Volume",
    calc: (val) => divide(val, 10000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x13,
    legacyName: "VIF_VOLUME",
    unit: "m³",
    description: "Volume",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x14,
    legacyName: "VIF_VOLUME",
    unit: "m³",
    description: "Volume",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x15,
    legacyName: "VIF_VOLUME",
    unit: "m³",
    description: "Volume",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x16,
    legacyName: "VIF_VOLUME",
    unit: "m³",
    description: "Volume",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x17,
    legacyName: "VIF_VOLUME",
    unit: "m³",
    description: "Volume",
    calc: (val) => multiply(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x18,
    legacyName: "VIF_MASS",
    unit: "kg",
    description: "Mass",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x19,
    legacyName: "VIF_MASS",
    unit: "kg",
    description: "Mass",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x1a,
    legacyName: "VIF_MASS",
    unit: "kg",
    description: "Mass",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x1b,
    legacyName: "VIF_MASS",
    unit: "kg",
    description: "Mass",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x1c,
    legacyName: "VIF_MASS",
    unit: "kg",
    description: "Mass",
    calc: (val) => multiply(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x1d,
    legacyName: "VIF_MASS",
    unit: "kg",
    description: "Mass",
    calc: (val) => multiply(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x1e,
    legacyName: "VIF_MASS",
    unit: "kg",
    description: "Mass",
    calc: (val) => multiply(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x1f,
    legacyName: "VIF_MASS",
    unit: "kg",
    description: "Mass",
    calc: (val) => multiply(val, 10000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x20,
    legacyName: "VIF_ON_TIME",
    unit: "s",
    description: "On Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x21,
    legacyName: "VIF_ON_TIME",
    unit: "min",
    description: "On Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x22,
    legacyName: "VIF_ON_TIME",
    unit: "h",
    description: "On Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x23,
    legacyName: "VIF_ON_TIME",
    unit: "d",
    description: "On Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x24,
    legacyName: "VIF_OP_TIME",
    unit: "s",
    description: "Operating Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x25,
    legacyName: "VIF_OP_TIME",
    unit: "min",
    description: "Operating Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x26,
    legacyName: "VIF_OP_TIME",
    unit: "h",
    description: "Operating Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x27,
    legacyName: "VIF_OP_TIME",
    unit: "d",
    description: "Operating Time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x28,
    legacyName: "VIF_ELECTRIC_POWER",
    unit: "W",
    description: "Power",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x29,
    legacyName: "VIF_ELECTRIC_POWER",
    unit: "W",
    description: "Power",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x2a,
    legacyName: "VIF_ELECTRIC_POWER",
    unit: "W",
    description: "Power",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x2b,
    legacyName: "VIF_ELECTRIC_POWER",
    unit: "W",
    description: "Power",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x2c,
    legacyName: "VIF_ELECTRIC_POWER",
    unit: "W",
    description: "Power",
    calc: (val) => multiply(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x2d,
    legacyName: "VIF_ELECTRIC_POWER",
    unit: "W",
    description: "Power",
    calc: (val) => multiply(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x2e,
    legacyName: "VIF_ELECTRIC_POWER",
    unit: "W",
    description: "Power",
    calc: (val) => multiply(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x2f,
    legacyName: "VIF_ELECTRIC_POWER",
    unit: "W",
    description: "Power",
    calc: (val) => multiply(val, 10000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x30,
    legacyName: "VIF_THERMAL_POWER",
    unit: "J/h",
    description: "Power",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x31,
    legacyName: "VIF_THERMAL_POWER",
    unit: "J/h",
    description: "Power",
    calc: (val) => multiply(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x32,
    legacyName: "VIF_THERMAL_POWER",
    unit: "J/h",
    description: "Power",
    calc: (val) => multiply(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x33,
    legacyName: "VIF_THERMAL_POWER",
    unit: "J/h",
    description: "Power",
    calc: (val) => multiply(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x34,
    legacyName: "VIF_THERMAL_POWER",
    unit: "J/h",
    description: "Power",
    calc: (val) => multiply(val, 10000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x35,
    legacyName: "VIF_THERMAL_POWER",
    unit: "J/h",
    description: "Power",
    calc: (val) => multiply(val, 100000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x36,
    legacyName: "VIF_THERMAL_POWER",
    unit: "J/h",
    description: "Power",
    calc: (val) => multiply(val, 1000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x37,
    legacyName: "VIF_THERMAL_POWER",
    unit: "J/h",
    description: "Power",
    calc: (val) => multiply(val, 10000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x38,
    legacyName: "VIF_VOLUME_FLOW",
    unit: "m³/h",
    description: "Volume Flow",
    calc: (val) => divide(val, 1000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x39,
    legacyName: "VIF_VOLUME_FLOW",
    unit: "m³/h",
    description: "Volume Flow",
    calc: (val) => divide(val, 100000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x3a,
    legacyName: "VIF_VOLUME_FLOW",
    unit: "m³/h",
    description: "Volume Flow",
    calc: (val) => divide(val, 10000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x3b,
    legacyName: "VIF_VOLUME_FLOW",
    unit: "m³/h",
    description: "Volume Flow",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x3c,
    legacyName: "VIF_VOLUME_FLOW",
    unit: "m³/h",
    description: "Volume Flow",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x3d,
    legacyName: "VIF_VOLUME_FLOW",
    unit: "m³/h",
    description: "Volume Flow",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x3e,
    legacyName: "VIF_VOLUME_FLOW",
    unit: "m³/h",
    description: "Volume Flow",
    calc: (val) => multiply(val, 1),
    apply: applyNumberDefault,
  },
  {
    vif: 0x3f,
    legacyName: "VIF_VOLUME_FLOW",
    unit: "m³/h",
    description: "Volume Flow",
    calc: (val) => multiply(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x40,
    legacyName: "VIF_VOLUME_FLOW_EXT1",
    unit: "m³/min",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 10000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x41,
    legacyName: "VIF_VOLUME_FLOW_EXT1",
    unit: "m³/min",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 1000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x42,
    legacyName: "VIF_VOLUME_FLOW_EXT1",
    unit: "m³/min",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 100000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x43,
    legacyName: "VIF_VOLUME_FLOW_EXT1",
    unit: "m³/min",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 10000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x44,
    legacyName: "VIF_VOLUME_FLOW_EXT1",
    unit: "m³/min",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x45,
    legacyName: "VIF_VOLUME_FLOW_EXT1",
    unit: "m³/min",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x46,
    legacyName: "VIF_VOLUME_FLOW_EXT1",
    unit: "m³/min",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x47,
    legacyName: "VIF_VOLUME_FLOW_EXT1",
    unit: "m³/min",
    description: "Volume Flow ext.",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x48,
    legacyName: "VIF_VOLUME_FLOW_EXT2",
    unit: "m³/s",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 1000000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x49,
    legacyName: "VIF_VOLUME_FLOW_EXT2",
    unit: "m³/s",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 100000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x4a,
    legacyName: "VIF_VOLUME_FLOW_EXT2",
    unit: "m³/s",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 10000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x4b,
    legacyName: "VIF_VOLUME_FLOW_EXT2",
    unit: "m³/s",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 1000000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x4c,
    legacyName: "VIF_VOLUME_FLOW_EXT2",
    unit: "m³/s",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 100000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x4d,
    legacyName: "VIF_VOLUME_FLOW_EXT2",
    unit: "m³/s",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 10000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x4e,
    legacyName: "VIF_VOLUME_FLOW_EXT2",
    unit: "m³/s",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x4f,
    legacyName: "VIF_VOLUME_FLOW_EXT2",
    unit: "m³/s",
    description: "Volume Flow ext.",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x50,
    legacyName: "VIF_MASS_FLOW",
    unit: "kg/h",
    description: "Mass Flow",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x51,
    legacyName: "VIF_MASS_FLOW",
    unit: "kg/h",
    description: "Mass Flow",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x52,
    legacyName: "VIF_MASS_FLOW",
    unit: "kg/h",
    description: "Mass Flow",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x53,
    legacyName: "VIF_MASS_FLOW",
    unit: "kg/h",
    description: "Mass Flow",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x54,
    legacyName: "VIF_MASS_FLOW",
    unit: "kg/h",
    description: "Mass Flow",
    calc: (val) => multiply(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x55,
    legacyName: "VIF_MASS_FLOW",
    unit: "kg/h",
    description: "Mass Flow",
    calc: (val) => multiply(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x56,
    legacyName: "VIF_MASS_FLOW",
    unit: "kg/h",
    description: "Mass Flow",
    calc: (val) => multiply(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x57,
    legacyName: "VIF_MASS_FLOW",
    unit: "kg/h",
    description: "Mass Flow",
    calc: (val) => multiply(val, 10000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x58,
    legacyName: "VIF_FLOW_TEMP",
    unit: "°C",
    description: "Flow Temperature",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x59,
    legacyName: "VIF_FLOW_TEMP",
    unit: "°C",
    description: "Flow Temperature",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x5a,
    legacyName: "VIF_FLOW_TEMP",
    unit: "°C",
    description: "Flow Temperature",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x5b,
    legacyName: "VIF_FLOW_TEMP",
    unit: "°C",
    description: "Flow Temperature",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x5c,
    legacyName: "VIF_RETURN_TEMP",
    unit: "°C",
    description: "Return Temperature",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x5d,
    legacyName: "VIF_RETURN_TEMP",
    unit: "°C",
    description: "Return Temperature",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x5e,
    legacyName: "VIF_RETURN_TEMP",
    unit: "°C",
    description: "Return Temperature",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x5f,
    legacyName: "VIF_RETURN_TEMP",
    unit: "°C",
    description: "Return Temperature",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x60,
    legacyName: "VIF_TEMP_DIFF",
    unit: "K",
    description: "Temperature Difference",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x61,
    legacyName: "VIF_TEMP_DIFF",
    unit: "K",
    description: "Temperature Difference",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x62,
    legacyName: "VIF_TEMP_DIFF",
    unit: "K",
    description: "Temperature Difference",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x63,
    legacyName: "VIF_TEMP_DIFF",
    unit: "K",
    description: "Temperature Difference",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x64,
    legacyName: "VIF_EXTERNAL_TEMP",
    unit: "°C",
    description: "External Temperature",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x65,
    legacyName: "VIF_EXTERNAL_TEMP",
    unit: "°C",
    description: "External Temperature",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x66,
    legacyName: "VIF_EXTERNAL_TEMP",
    unit: "°C",
    description: "External Temperature",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x67,
    legacyName: "VIF_EXTERNAL_TEMP",
    unit: "°C",
    description: "External Temperature",
    calc: (val) => multiply(val, 1),
    apply: applyNumberDefault,
  },
  {
    vif: 0x68,
    legacyName: "VIF_PRESSURE",
    unit: "bar",
    description: "Pressure",
    calc: (val) => divide(val, 1000),
    apply: applyNumberDefault,
  },
  {
    vif: 0x69,
    legacyName: "VIF_PRESSURE",
    unit: "bar",
    description: "Pressure",
    calc: (val) => divide(val, 100),
    apply: applyNumberDefault,
  },
  {
    vif: 0x6a,
    legacyName: "VIF_PRESSURE",
    unit: "bar",
    description: "Pressure",
    calc: (val) => divide(val, 10),
    apply: applyNumberDefault,
  },
  {
    vif: 0x6b,
    legacyName: "VIF_PRESSURE",
    unit: "bar",
    description: "Pressure",
    calc: (val) => multiply(val, 1),
    apply: applyNumberDefault,
  },
  {
    vif: 0x6c,
    legacyName: "VIF_TIME_POINT_DATE",
    unit: "",
    description: "Time point",
    calc: (val) => val,
    apply: applyDateDefault,
  },
  {
    vif: 0x6d,
    legacyName: "VIF_TIME_POINT_DATE_TIME",
    unit: "",
    description: "Time point",
    calc: (val) => val,
    apply: applyDateTimeDefault,
  },
  {
    vif: 0x6e,
    legacyName: "VIF_HCA",
    unit: "",
    description: "Units for H.C.A.",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  //Reserved primary VIF 0x6f
  {
    vif: 0x70,
    legacyName: "VIF_AVERAGING_DURATION",
    unit: "s",
    description: "Averaging Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x71,
    legacyName: "VIF_AVERAGING_DURATION",
    unit: "min",
    description: "Averaging Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x72,
    legacyName: "VIF_AVERAGING_DURATION",
    unit: "h",
    description: "Averaging Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x73,
    legacyName: "VIF_AVERAGING_DURATION",
    unit: "d",
    description: "Averaging Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x74,
    legacyName: "VIF_ACTUALITY_DURATION",
    unit: "s",
    description: "Actuality Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x75,
    legacyName: "VIF_ACTUALITY_DURATION",
    unit: "min",
    description: "Actuality Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x76,
    legacyName: "VIF_ACTUALITY_DURATION",
    unit: "h",
    description: "Actuality Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x77,
    legacyName: "VIF_ACTUALITY_DURATION",
    unit: "d",
    description: "Actuality Duration",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x78,
    legacyName: "VIF_FABRICATION_NO",
    unit: "",
    description: "Fabrication No",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x79,
    legacyName: "VIF_OWNER_NO",
    unit: "",
    description: "Owner No",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x7a,
    legacyName: "VIF_BUS_ADDRESS",
    unit: "",
    description: "Bus Address",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
];
