import {
  applyBufferOrNumberDefault,
  applyDateOrDateTimeDefault,
  applyDateTimeDefault,
  applyNumberDefault,
  applyNumberOrStringifyDefault,
  applyStringifyDefault,
} from "@/helper/vifHelper";
import type { VIFDescriptor } from "@/types";
import { decadeRange } from "@/vif/vifRange";

export const fdVifs: VIFDescriptor[] = [
  ...decadeRange(0x00, 4, -3, "VIF_CREDIT", "€", "Credit"),
  ...decadeRange(0x04, 4, -3, "VIF_DEBIT", "€", "Debit"),
  {
    vif: 0x08,
    legacyName: "VIF_ACCESS_NO",
    unit: "",
    description: "Access number (transmission count)",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x09,
    legacyName: "VIF_MEDIUM",
    unit: "",
    description: "Device type",
    calc: (val) => val,
    apply: applyStringifyDefault,
  },
  {
    vif: 0x0a,
    legacyName: "VIF_MANUFACTURER",
    unit: "",
    description: "Manufacturer",
    calc: (val) => val,
    apply: applyStringifyDefault,
  },
  {
    vif: 0x0b,
    legacyName: "VIF_PARAM_SET_IDENTIFICATION",
    unit: "",
    description: "Parameter set identification",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x0c,
    legacyName: "VIF_MODEL_VERSION",
    unit: "",
    description: "Model / Version",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x0d,
    legacyName: "VIF_HARDWARE_VERSION",
    unit: "",
    description: "Hardware version #",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x0e,
    legacyName: "VIF_FIRMWARE_VERSION",
    unit: "",
    description: "Firmware version #",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x0f,
    legacyName: "VIF_SOFTWARE_VERSION",
    unit: "",
    description: "Software version #",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x10,
    legacyName: "VIF_CUSTOMER_LOCATION",
    unit: "",
    description: "Customer location",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x11,
    legacyName: "VIF_CUSTOMER",
    unit: "",
    description: "Customer",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x12,
    legacyName: "VIF_ACCESS_CODE_USER",
    unit: "",
    description: "Access Code User",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x13,
    legacyName: "VIF_ACCESS_CODE_OPERATOR",
    unit: "",
    description: "Access Code Operator",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x14,
    legacyName: "VIF_ACCESS_CODE_SYS_OPERATOR",
    unit: "",
    description: "Access Code Sytem Operator",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x15,
    legacyName: "VIF_ACCESS_CODE_DEVELOPER",
    unit: "",
    description: "Access Code Developer",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x16,
    legacyName: "VIF_PASSWORD",
    unit: "",
    description: "Password",
    calc: (val) => val,
    apply: applyNumberOrStringifyDefault,
  },
  {
    vif: 0x17,
    legacyName: "VIF_ERROR_FLAGS",
    unit: "",
    description: "Error flags (binary)",
    calc: (val) => val,
    apply: applyBufferOrNumberDefault,
  },
  {
    vif: 0x18,
    legacyName: "VIF_ERROR_MASK",
    unit: "",
    description: "Error mask",
    calc: (val) => val,
    apply: applyBufferOrNumberDefault,
  },
  {
    vif: 0x1a,
    legacyName: "VIF_DIGITAL_OUTPUT_BINARY",
    unit: "",
    description: "Digital Output (binary)",
    calc: (val) => val,
    apply: applyBufferOrNumberDefault,
  },
  {
    vif: 0x1b,
    legacyName: "VIF_DIGITAL_INPUT_BINARY",
    unit: "",
    description: "Digital Input (binary) ",
    calc: (val) => val,
    apply: applyBufferOrNumberDefault,
  },
  {
    vif: 0x1c,
    legacyName: "VIF_BAUDRATE",
    unit: "baud",
    description: "Baudrate",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x1d,
    legacyName: "VIF_RESPONSE_DELAY_TIME",
    unit: "bittimes",
    description: "Response delay time",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x1e,
    legacyName: "VIF_RETRY",
    unit: "",
    description: "Retry",
    calc: (val) => val,
    apply: applyBufferOrNumberDefault,
  },
  {
    vif: 0x20,
    legacyName: "VIF_FIRST_STORAGE_CYCLIC",
    unit: "",
    description: "First storage # for cyclic storage",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x21,
    legacyName: "VIF_LAST_STORAGE_CYCLIC",
    unit: "",
    description: "Last storage # for cyclic storage",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x22,
    legacyName: "VIF_SIZE_STORAGE_BLOCK",
    unit: "",
    description: "Size of storage block",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x24,
    legacyName: "VIF_SIZE_STORAGE_INTERVAL",
    unit: "s",
    description: "Storage interval ",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x25,
    legacyName: "VIF_SIZE_STORAGE_INTERVAL",
    unit: "min",
    description: "Storage interval ",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x26,
    legacyName: "VIF_SIZE_STORAGE_INTERVAL",
    unit: "h",
    description: "Storage interval ",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x27,
    legacyName: "VIF_SIZE_STORAGE_INTERVAL",
    unit: "d",
    description: "Storage interval ",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x28,
    legacyName: "VIF_SIZE_STORAGE_INTERVAL",
    unit: "month",
    description: "Storage interval",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x29,
    legacyName: "VIF_SIZE_STORAGE_INTERVAL",
    unit: "year",
    description: "Storage interval",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x2c,
    legacyName: "VIF_DURATION_SINCE_LAST_READ",
    unit: "s",
    description: "Duration since last readout",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x2d,
    legacyName: "VIF_DURATION_SINCE_LAST_READ",
    unit: "min",
    description: "Duration since last readout",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x2e,
    legacyName: "VIF_DURATION_SINCE_LAST_READ",
    unit: "h",
    description: "Duration since last readout",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x2f,
    legacyName: "VIF_DURATION_SINCE_LAST_READ",
    unit: "d",
    description: "Duration since last readout",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x30,
    legacyName: "VIF_TARIFF_START",
    unit: "",
    description: "Start of tariff",
    calc: (val) => val,
    apply: applyDateOrDateTimeDefault,
  },
  {
    vif: 0x31,
    legacyName: "VIF_TARIFF_DURATION",
    unit: "min",
    description: "Duration of tariff",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x32,
    legacyName: "VIF_TARIFF_DURATION",
    unit: "h",
    description: "Duration of tariff",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x33,
    legacyName: "VIF_TARIFF_DURATION",
    unit: "d",
    description: "Duration of tariff",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x34,
    legacyName: "VIF_TARIFF_PERIOD",
    unit: "s",
    description: "Period of tariff",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x35,
    legacyName: "VIF_TARIFF_PERIOD",
    unit: "min",
    description: "Period of tariff",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x36,
    legacyName: "VIF_TARIFF_PERIOD",
    unit: "h",
    description: "Period of tariff",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x37,
    legacyName: "VIF_TARIFF_PERIOD",
    unit: "d",
    description: "Period of tariff",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x38,
    legacyName: "VIF_TARIFF_PERIOD",
    unit: "months",
    description: "Period of tariff",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x39,
    legacyName: "VIF_TARIFF_PERIOD",
    unit: "years",
    description: "Period of tariff",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x3a,
    legacyName: "VIF_DIMENSIONLESS",
    unit: "",
    description: "Dimensionless",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  ...decadeRange(0x40, 16, -9, "VIF_ELECTRICAL_VOLTAGE", "V", "Voltage"),
  ...decadeRange(0x50, 16, -12, "VIF_ELECTRICAL_CURRENT", "A", "Current"),
  {
    vif: 0x60,
    legacyName: "VIF_RESET_COUNTER",
    unit: "",
    description: "Reset counter",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x61,
    legacyName: "VIF_CUMULATION_COUNTER",
    unit: "",
    description: "Cumulation counter",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x62,
    legacyName: "VIF_CONTROL_SIGNAL",
    unit: "",
    description: "Control signal",
    calc: (val) => val,
    apply: applyStringifyDefault,
  },
  {
    vif: 0x63,
    legacyName: "VIF_DAY_OF_WEEK",
    unit: "",
    description: "Day of week",
    calc: (val) => val,
    apply: applyStringifyDefault,
  },
  {
    vif: 0x64,
    legacyName: "VIF_WEEK_NUMBER",
    unit: "",
    description: "Week number",
    calc: (val) => val,
    apply: applyStringifyDefault,
  },
  {
    vif: 0x65,
    legacyName: "VIF_TIME_POINT_DAY_CHANGE",
    unit: "",
    description: "Time point of day change",
    calc: (val) => val,
    apply: applyDateTimeDefault,
  },
  {
    vif: 0x66,
    legacyName: "VIF_STATE_OF_PARAM_ACTIVATION",
    unit: "",
    description: "State of parameter activation",
    calc: (val) => val,
    apply: applyStringifyDefault,
  },
  {
    vif: 0x67,
    legacyName: "VIF_SPECIAL_SUPPLIER_INFO",
    unit: "",
    description: "Special supplier information",
    calc: (val) => val,
    apply: applyStringifyDefault,
  },
  {
    vif: 0x68,
    legacyName: "VIF_DURATION_SINCE_CUMULATION",
    unit: "s",
    description: "Duration since last cumulation",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x69,
    legacyName: "VIF_DURATION_SINCE_CUMULATION",
    unit: "min",
    description: "Duration since last cumulation",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x6a,
    legacyName: "VIF_DURATION_SINCE_CUMULATION",
    unit: "h",
    description: "Duration since last cumulation",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x6b,
    legacyName: "VIF_DURATION_SINCE_CUMULATION",
    unit: "d",
    description: "Duration since last cumulation",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x6c,
    legacyName: "VIF_OPERATING_TIME_BATTERY",
    unit: "s",
    description: "Operating time battery",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x6d,
    legacyName: "VIF_OPERATING_TIME_BATTERY",
    unit: "min",
    description: "Operating time battery",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x6e,
    legacyName: "VIF_OPERATING_TIME_BATTERY",
    unit: "h",
    description: "Operating time battery",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x6f,
    legacyName: "VIF_OPERATING_TIME_BATTERY",
    unit: "d",
    description: "Operating time battery",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
  {
    vif: 0x70,
    legacyName: "VIF_DATETIME_BATTERY_CHANGE",
    unit: "",
    description: "Date and time of battery change",
    calc: (val) => val,
    apply: applyDateTimeDefault,
  },
  {
    vif: 0x71,
    legacyName: "VIF_RECEPTION_LEVEL",
    unit: "dBm",
    description: "Reception level",
    calc: (val) => val,
    apply: applyNumberDefault,
  },
];
