import {
  add,
  applyNumberEvaluated,
  divide,
  extendDescription,
  extendDescriptionReplaceDateOrTime,
  extendUnit,
  multiply,
  noop,
} from "@/helper/vifHelper";
import type { VIFEDescriptor } from "@/types";

// The codes up to 0x1f are record errors: the record still states the same
// quantity, but its value cannot be trusted - so they have no name, which would
// move the value to another state, but an error.
export const vifExtensions: VIFEDescriptor[] = [
  {
    vif: 0x0,
    legacyName: "VIF_ERROR_NONE",
    description: "No error",
    apply: noop,
  },
  {
    vif: 0x1,
    legacyName: "VIF_TOO_MANY_DIFE",
    error: "too_many_difes",
    description: "Too many DIFEs",
    apply: extendDescription,
  },
  {
    vif: 0x2,
    legacyName: "VIF_STORAGE_NUM_NOT_IMPL",
    error: "storage_number_not_implemented",
    description: "Storage number not implemented",
    apply: extendDescription,
  },
  {
    vif: 0x3,
    legacyName: "VIF_UNIT_NUM_NOT_IMPL",
    error: "unit_number_not_implemented",
    description: "Unit number not implemented",
    apply: extendDescription,
  },
  {
    vif: 0x4,
    legacyName: "VIF_TARIFF_NUM_NOT_IMPL",
    error: "tariff_number_not_implemented",
    description: "Tariff number not implemented",
    apply: extendDescription,
  },
  {
    vif: 0x5,
    legacyName: "VIF_FUNCTION_NOT_IMPL",
    error: "function_not_implemented",
    description: "Function not implemented",
    apply: extendDescription,
  },
  {
    vif: 0x6,
    legacyName: "VIF_DATA_CLASS_NOT_IMPL",
    error: "data_class_not_implemented",
    description: "Data class not implemented",
    apply: extendDescription,
  },
  {
    vif: 0x7,
    legacyName: "VIF_DATA_SIZENOT_IMPL",
    error: "data_size_not_implemented",
    description: "Data size not implemented",
    apply: extendDescription,
  },
  {
    vif: 0xb,
    legacyName: "VIF_TOO_MANY_VIFE",
    error: "too_many_vifes",
    description: "Too many VIFEs",
    apply: extendDescription,
  },
  {
    vif: 0xc,
    legacyName: "VIF_ILLEGAL_VIF_GROUP",
    error: "illegal_vif_group",
    description: "Illegal VIF-Group",
    apply: extendDescription,
  },
  {
    vif: 0xd,
    legacyName: "VIF_ILLEGAL_VIF_EXP",
    error: "illegal_vif_exponent",
    description: "Illegal VIF-Exponent",
    apply: extendDescription,
  },
  {
    vif: 0xe,
    legacyName: "VIF_VIF_DIF_MISMATCH",
    error: "vif_dif_mismatch",
    description: "VIF/DIF mismatch",
    apply: extendDescription,
  },
  {
    vif: 0xf,
    legacyName: "VIF_ACTION_NOT_IMPL",
    error: "unimplemented_action",
    description: "Unimplemented action",
    apply: extendDescription,
  },
  {
    vif: 0x15,
    legacyName: "VIF_NO_DATA",
    error: "no_data_available",
    description: "No data available (undefined value)",
    apply: extendDescription,
  },
  {
    vif: 0x16,
    legacyName: "VIF_DATA_OVERFLOW",
    error: "data_overflow",
    description: "Data overflow",
    apply: extendDescription,
  },
  {
    vif: 0x17,
    legacyName: "VIF_DATA_UNDERFLOW",
    error: "data_underflow",
    description: "Data underflow",
    apply: extendDescription,
  },
  {
    vif: 0x18,
    legacyName: "VIF_DATA_ERROR",
    error: "data_error",
    description: "Data error",
    apply: extendDescription,
  },
  {
    vif: 0x1c,
    legacyName: "VIF_PREMATURE_END",
    error: "premature_end_of_record",
    description: "Premature end of record",
    apply: extendDescription,
  },
  {
    vif: 0x1d,
    legacyName: "VIF_STANDARD_CONFORM",
    description: "Standard conform",
    apply: extendDescription,
  },
  {
    vif: 0x20,
    legacyName: "VIF_PER_SECOND",
    name: "per_second",
    unit: "/ s",
    apply: extendUnit,
  },
  {
    vif: 0x21,
    legacyName: "VIF_PER_MINUTE",
    name: "per_minute",
    unit: "/ min",
    apply: extendUnit,
  },
  {
    vif: 0x22,
    legacyName: "VIF_PER_HOUR",
    name: "per_hour",
    unit: "/ h",
    apply: extendUnit,
  },
  {
    vif: 0x23,
    legacyName: "VIF_PER_DAY",
    name: "per_day",
    unit: "/ d",
    apply: extendUnit,
  },
  {
    vif: 0x24,
    legacyName: "VIF_PER_WEEK",
    name: "per_week",
    unit: "/ week",
    apply: extendUnit,
  },
  {
    vif: 0x25,
    legacyName: "VIF_PER_MONTH",
    name: "per_month",
    unit: "/ month",
    apply: extendUnit,
  },
  {
    vif: 0x26,
    legacyName: "VIF_PER_YEAR",
    name: "per_year",
    unit: "/ year",
    apply: extendUnit,
  },
  {
    vif: 0x27,
    legacyName: "VIF_PER_REVOLUTION",
    name: "per_revolution",
    unit: "/ revolution/measurement",
    apply: extendUnit,
  },
  {
    vif: 0x28,
    legacyName: "VIF_PER_INCREMENT_INPUT_0",
    name: "per_pulse_input_0",
    unit: "increment per pulse on input channnel 0",
    apply: extendUnit,
  },
  {
    vif: 0x29,
    legacyName: "VIF_PER_INCREMENT_INPUT_1",
    name: "per_pulse_input_1",
    unit: "increment per pulse on input channnel 1",
    apply: extendUnit,
  },
  {
    vif: 0x2a,
    legacyName: "VIF_PER_INCREMENT_OUTPUT_0",
    name: "per_pulse_output_0",
    unit: "increment per pulse on output channnel 0",
    apply: extendUnit,
  },
  {
    vif: 0x2b,
    legacyName: "VIF_PER_INCREMENT_OUTPUT_1",
    name: "per_pulse_output_1",
    unit: "increment per pulse on output channnel 1",
    apply: extendUnit,
  },
  {
    vif: 0x2c,
    legacyName: "VIF_PER_LITER",
    name: "per_liter",
    unit: "/ L",
    apply: extendUnit,
  },
  {
    vif: 0x2d,
    legacyName: "VIF_PER_CUBICMETER",
    name: "per_cubic_meter",
    unit: "/ m³",
    apply: extendUnit,
  },
  {
    vif: 0x2e,
    legacyName: "VIF_PER_KILOGRAM",
    name: "per_kilogram",
    unit: "/ kg",
    apply: extendUnit,
  },
  {
    vif: 0x2f,
    legacyName: "VIF_PER_KELVIN",
    name: "per_kelvin",
    unit: "/ K",
    apply: extendUnit,
  },
  {
    vif: 0x30,
    legacyName: "VIF_PER_KWH",
    name: "per_kwh",
    unit: "/ kWh",
    apply: extendUnit,
  },
  {
    vif: 0x31,
    legacyName: "VIF_PER_GIGAJOULE",
    name: "per_gigajoule",
    unit: "/ GJ",
    apply: extendUnit,
  },
  {
    vif: 0x32,
    legacyName: "VIF_PER_KILOWATT",
    name: "per_kilowatt",
    unit: "/ kW",
    apply: extendUnit,
  },
  {
    vif: 0x33,
    legacyName: "VIF_PER_KL",
    name: "per_kelvin_liter",
    unit: "/ (K*L)",
    apply: extendUnit,
  },
  {
    vif: 0x34,
    legacyName: "VIF_PER_VOLT",
    name: "per_volt",
    unit: "/ V",
    apply: extendUnit,
  },
  {
    vif: 0x35,
    legacyName: "VIF_PER_AMPERE",
    name: "per_ampere",
    unit: "/ A",
    apply: extendUnit,
  },
  {
    vif: 0x36,
    legacyName: "VIF_TIMES_SEC",
    name: "times_second",
    unit: "* s",
    apply: extendUnit,
  },
  {
    vif: 0x37,
    legacyName: "VIF_TIMES_SEC_V",
    name: "times_second_per_volt",
    unit: "* s / V",
    apply: extendUnit,
  },
  {
    vif: 0x38,
    legacyName: "VIF_TIMES_SEC_A",
    name: "times_second_per_ampere",
    unit: "* s / A",
    apply: extendUnit,
  },
  {
    vif: 0x39,
    legacyName: "VIF_START_DATE_TIME",
    name: "start",
    description: "start date or time of",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x3a,
    legacyName: "VIF_UNCORRECTED_UNIT",
    name: "uncorrected",
    description: "VIF contains uncorrected unit instead of corrected unit",
    apply: extendDescription,
  },
  {
    vif: 0x3b,
    legacyName: "VIF_ACCUMULATION_IF_POSITIVE",
    name: "positive",
    description: "Accumulation only if positive contribution",
    apply: extendDescription,
  },
  {
    vif: 0x3c,
    legacyName: "VIF_ACCUMULATION_ABS_NEGATIVE",
    name: "negative",
    description: "Accumulation of abs value only if negative contributions",
    apply: extendDescription,
  },
  {
    vif: 0x40,
    legacyName: "VIF_LOWER_LIMIT_VALUE",
    name: "lower_limit_value",
    description: "lower limit value",
    apply: extendDescription,
  },
  {
    vif: 0x41,
    legacyName: "VIF_EXCEEDS_LOWER_LIMIT",
    name: "number_of_exceeds_of_lower_limit",
    description: "# of exceeds of lower limit",
    apply: extendDescription,
  },
  {
    vif: 0x42,
    legacyName: "VIF_TIME_BEGIN_FIRST_LOWER",
    name: "begin_of_first_lower_limit_exceed",
    description: "date or time of begin of first lower limit exceed",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x43,
    legacyName: "VIF_TIME_END_FIRST_LOWER",
    name: "end_of_first_lower_limit_exceed",
    description: "date or time of end of first lower limit exceed",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x46,
    legacyName: "VIF_TIME_BEGIN_LAST_LOWER",
    name: "begin_of_last_lower_limit_exceed",
    description: "date or time of begin of last lower limit exceed",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x47,
    legacyName: "VIF_TIME_END_LAST_LOWER",
    name: "end_of_last_lower_limit_exceed",
    description: "date or time of end of last lower limit exceed",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x48,
    legacyName: "VIF_UPPER_LIMIT_VALUE",
    name: "upper_limit_value",
    description: "upper limit value",
    apply: extendDescription,
  },
  {
    vif: 0x49,
    legacyName: "VIF_EXCEEDS_UPPER_LIMIT",
    name: "number_of_exceeds_of_upper_limit",
    description: "# of exceeds of upper limit",
    apply: extendDescription,
  },
  {
    vif: 0x4a,
    legacyName: "VIF_TIME_BEGIN_FIRST_UPPER",
    name: "begin_of_first_upper_limit_exceed",
    description: "date or time of begin of first upper limit exceed",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x4b,
    legacyName: "VIF_TIME_END_FIRST_UPPER",
    name: "end_of_first_upper_limit_exceed",
    description: "date or time of end of first upper limit exceed",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x4e,
    legacyName: "VIF_TIME_BEGIN_LAST_UPPER",
    name: "begin_of_last_upper_limit_exceed",
    description: "date or time of begin of last upper limit exceed",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x4f,
    legacyName: "VIF_TIME_END_LAST_UPPER",
    name: "end_of_last_upper_limit_exceed",
    description: "date or time of end of last upper limit exceed",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x50,
    legacyName: "VIF_DUR_FIRST_LOWER_EXCEED",
    name: "duration_of_first_lower_limit_exceed",
    description: "Duration of first lower limit exceed: 0",
    apply: extendDescription,
  },
  {
    vif: 0x51,
    legacyName: "VIF_DUR_FIRST_LOWER_EXCEED",
    name: "duration_of_first_lower_limit_exceed",
    description: "Duration of first lower limit exceed: 1",
    apply: extendDescription,
  },
  {
    vif: 0x52,
    legacyName: "VIF_DUR_FIRST_LOWER_EXCEED",
    name: "duration_of_first_lower_limit_exceed",
    description: "Duration of first lower limit exceed: 2",
    apply: extendDescription,
  },
  {
    vif: 0x53,
    legacyName: "VIF_DUR_FIRST_LOWER_EXCEED",
    name: "duration_of_first_lower_limit_exceed",
    description: "Duration of first lower limit exceed: 3",
    apply: extendDescription,
  },
  {
    vif: 0x54,
    legacyName: "VIF_DUR_LAST_LOWER_EXCEED",
    name: "duration_of_last_lower_limit_exceed",
    description: "Duration of last lower limit exceed: 0",
    apply: extendDescription,
  },
  {
    vif: 0x55,
    legacyName: "VIF_DUR_LAST_LOWER_EXCEED",
    name: "duration_of_last_lower_limit_exceed",
    description: "Duration of last lower limit exceed: 1",
    apply: extendDescription,
  },
  {
    vif: 0x56,
    legacyName: "VIF_DUR_LAST_LOWER_EXCEED",
    name: "duration_of_last_lower_limit_exceed",
    description: "Duration of last lower limit exceed: 2",
    apply: extendDescription,
  },
  {
    vif: 0x57,
    legacyName: "VIF_DUR_LAST_LOWER_EXCEED",
    name: "duration_of_last_lower_limit_exceed",
    description: "Duration of last lower limit exceed: 3",
    apply: extendDescription,
  },
  {
    vif: 0x58,
    legacyName: "VIF_DUR_FIRST_UPPER_EXCEED",
    name: "duration_of_first_upper_limit_exceed",
    description: "Duration of first upper limit exceed: 0",
    apply: extendDescription,
  },
  {
    vif: 0x59,
    legacyName: "VIF_DUR_FIRST_UPPER_EXCEED",
    name: "duration_of_first_upper_limit_exceed",
    description: "Duration of first upper limit exceed: 1",
    apply: extendDescription,
  },
  {
    vif: 0x5a,
    legacyName: "VIF_DUR_FIRST_UPPER_EXCEED",
    name: "duration_of_first_upper_limit_exceed",
    description: "Duration of first upper limit exceed: 2",
    apply: extendDescription,
  },
  {
    vif: 0x5b,
    legacyName: "VIF_DUR_FIRST_UPPER_EXCEED",
    name: "duration_of_first_upper_limit_exceed",
    description: "Duration of first upper limit exceed: 3",
    apply: extendDescription,
  },
  {
    vif: 0x5c,
    legacyName: "VIF_DUR_LAST_UPPER_EXCEED",
    name: "duration_of_last_upper_limit_exceed",
    description: "Duration of last upper limit exceed: 0",
    apply: extendDescription,
  },
  {
    vif: 0x5d,
    legacyName: "VIF_DUR_LAST_UPPER_EXCEED",
    name: "duration_of_last_upper_limit_exceed",
    description: "Duration of last upper limit exceed: 1",
    apply: extendDescription,
  },
  {
    vif: 0x5e,
    legacyName: "VIF_DUR_LAST_UPPER_EXCEED",
    name: "duration_of_last_upper_limit_exceed",
    description: "Duration of last upper limit exceed: 2",
    apply: extendDescription,
  },
  {
    vif: 0x5f,
    legacyName: "VIF_DUR_LAST_UPPER_EXCEED",
    name: "duration_of_last_upper_limit_exceed",
    description: "Duration of last upper limit exceed: 3",
    apply: extendDescription,
  },
  {
    vif: 0x60,
    legacyName: "VIF_DURATION_FIRST",
    name: "duration_of_first",
    description: "Duration of first: 0",
    apply: extendDescription,
  },
  {
    vif: 0x61,
    legacyName: "VIF_DURATION_FIRST",
    name: "duration_of_first",
    description: "Duration of first: 1",
    apply: extendDescription,
  },
  {
    vif: 0x62,
    legacyName: "VIF_DURATION_FIRST",
    name: "duration_of_first",
    description: "Duration of first: 2",
    apply: extendDescription,
  },
  {
    vif: 0x63,
    legacyName: "VIF_DURATION_FIRST",
    name: "duration_of_first",
    description: "Duration of first: 3",
    apply: extendDescription,
  },
  {
    vif: 0x64,
    legacyName: "VIF_DURATION_LAST",
    name: "duration_of_last",
    description: "Duration of last: 0",
    apply: extendDescription,
  },
  {
    vif: 0x65,
    legacyName: "VIF_DURATION_LAST",
    name: "duration_of_last",
    description: "Duration of last: 1",
    apply: extendDescription,
  },
  {
    vif: 0x66,
    legacyName: "VIF_DURATION_LAST",
    name: "duration_of_last",
    description: "Duration of last: 2",
    apply: extendDescription,
  },
  {
    vif: 0x67,
    legacyName: "VIF_DURATION_LAST",
    name: "duration_of_last",
    description: "Duration of last: 3",
    apply: extendDescription,
  },
  {
    vif: 0x6a,
    legacyName: "VIF_TIME_FIRST_BEGIN",
    name: "first_begin",
    description: "date or time of first begin",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x6b,
    legacyName: "VIF_TIME_FIRST_END",
    name: "first_end",
    description: "date or time of first end",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x6e,
    legacyName: "VIF_TIME_LAST_BEGIN",
    name: "last_begin",
    description: "date or time of last begin",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x6f,
    legacyName: "VIF_TIME_LAST_END",
    name: "last_end",
    description: "date or time of last end",
    apply: extendDescriptionReplaceDateOrTime,
  },
  {
    vif: 0x70,
    legacyName: "VIF_CORRECTION_MULT",
    calc: (val) => divide(val, 1000000),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x71,
    legacyName: "VIF_CORRECTION_MULT",
    calc: (val) => divide(val, 100000),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x72,
    legacyName: "VIF_CORRECTION_MULT",
    calc: (val) => divide(val, 10000),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x73,
    legacyName: "VIF_CORRECTION_MULT",
    calc: (val) => divide(val, 1000),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x74,
    legacyName: "VIF_CORRECTION_MULT",
    calc: (val) => divide(val, 100),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x75,
    legacyName: "VIF_CORRECTION_MULT",
    calc: (val) => divide(val, 10),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x76,
    legacyName: "VIF_CORRECTION_MULT",
    calc: (val) => val,
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x77,
    legacyName: "VIF_CORRECTION_MULT",
    calc: (val) => multiply(val, 10),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x78,
    legacyName: "VIF_CORRECTION_ADD",
    calc: (val) => add(val, 0.001),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x79,
    legacyName: "VIF_CORRECTION_ADD",
    calc: (val) => add(val, 0.01),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x7a,
    legacyName: "VIF_CORRECTION_ADD",
    calc: (val) => add(val, 0.1),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x7b,
    legacyName: "VIF_CORRECTION_ADD",
    calc: (val) => add(val, 1),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x7d,
    legacyName: "VIF_CORRECTION_MULT1000",
    calc: (val) => multiply(val, 1000),
    apply: applyNumberEvaluated,
  },
  {
    vif: 0x7e,
    legacyName: "VIF_FUTURE_VALUE",
    name: "future_value",
    description: "future value",
    apply: extendDescription,
  },
  {
    vif: 0x7f,
    legacyName: "VIF_MANUFACTURER_SPECIFIC",
    description: "next VIFEs and data of this block are maufacturer specific",
    apply: extendDescription,
  },
];
