export const DATA_LINK_LAYER_SIZE = 10;

export const FRAME_A_BLOCK_SIZE = 16;
export const FRAME_B_BLOCK_SIZE = 128;

export const VALID_DEVICES_TYPES = {
  0x00: "Other",
  0x01: "Oil",
  0x02: "Electricity",
  0x03: "Gas",
  0x04: "Heat",
  0x05: "Steam",
  0x06: "Warm Water (30 °C ... 90 °C)",
  0x07: "Water",
  0x08: "Heat Cost Allocator",
  0x09: "Compressed Air",
  0x0a: "Cooling load meter (Volume measured at return temperature: outlet)",
  0x0b: "Cooling load meter (Volume measured at flow temperature: inlet)",
  0x0c: "Heat (Volume measured at flow temperature: inlet)",
  0x0d: "Heat / Cooling load meter",
  0x0e: "Bus / System component",
  0x0f: "Unknown Medium",
  0x10: "Reserved for utility meter",
  0x11: "Reserved for utility meter",
  0x12: "Reserved for utility meter",
  0x13: "Reserved for utility meter",
  0x14: "Calorific value",
  0x15: "Hot water (> 90 °C)",
  0x16: "Cold water",
  0x17: "Dual register (hot/cold) Water meter",
  0x18: "Pressure",
  0x19: "A/D Converter",
  0x1a: "Smokedetector",
  0x1b: "Room sensor (e.g. temperature or humidity)",
  0x1c: "Gasdetector",
  0x1d: "Reserved for sensors",
  0x1e: "Reserved for sensors",
  0x1f: "Reserved for sensors",
  0x20: "Breaker (electricity)",
  0x21: "Valve (gas)",
  0x22: "Reserved for switching devices",
  0x23: "Reserved for switching devices",
  0x24: "Reserved for switching devices",
  0x25: "Customer unit (Display device)",
  0x26: "Reserved for customer units",
  0x27: "Reserved for customer units",
  0x28: "Waste water",
  0x29: "Garbage",
  0x2a: "Carbon dioxide",
  0x2b: "Environmental meter",
  0x2c: "Environmental meter",
  0x2d: "Environmental meter",
  0x2e: "Environmental meter",
  0x2f: "Environmental meter",
  0x31: "OMS MUC",
  0x32: "OMS unidirectional repeater",
  0x33: "OMS bidirectional repeater",
  0x37: "Radio converter (Meter side)",
  0x43: "Heat meter (TCH)",
  0x62: "Hot water meter (TCH)",
  0x72: "Cold water meter (TCH)",
  0x80: "Heat cost allocator (TCH)",
  0xf0: "Smoke detector (TCH)",
};
